from pk_internal_tools.pk_functions.kill_window_by_title_via_wind32con import kill_window_by_title_via_wind32con

def ensure_window_killed_by_title(window_title):
    kill_window_by_title_via_wind32con(window_title)
